[phases.setup]
nixPkgs = ["python311"]  # Adjust the Python version if needed

[phases.install]
cmds = [
  "npm install",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start & python main.py"

